### ISSUE TITLE
Support hx-on

### ISSUE THREAD

**Issue by Smithx10** [maragudk/gomponents-htmx#9]
https://htmx.org/attributes/hx-on/

**Comment by markuswustenberg** [comment]
Hi @Smithx10. I'm currently on paternity leave and will have a proper look at this in a few weeks.

**Comment by Smithx10** [comment]
Sounds good, congratulations!!!

Wondering if we should enum all the different event types / modifiers etc.

**Comment by markuswustenberg** [comment]
@Smithx10 thanks. 😊

I don't think I'll add string constants at this point, because there are many and I'd rather not have to keep up with any changes. I've come to the same conclusion in the core gomponents library, and I don't really mind the string literals too much. They're quite readable IMO, and typos are often spotted quickly. Users are of course free to create their own constants.
